### ISSUE TITLE
Event end block gained new fields in recent versions

### ISSUE THREAD

**Issue by maxnoe** [cta-observatory/pycorsikaio#13]
The event end block gained additional fields in recent versions (need to check which versions introduced which fields).

**Comment by maxnoe** [comment]
By asking the maintainers for them via email. But I think first adding support for the versions where we definitely know these fields are contained in is fine I think. I think they were introduced with 7.x, but not sure.

**Comment by AndreaNegro953** [comment]
There is actually a problem in adding this solution. From what I can understand, the EVTE subblock does not have a version field, so it is not possible to read the CORSIKA version from the block as done for the other blocks in which dtypes are different for different versions of CORSIKA.

**Comment by maxnoe** [comment]
Hi @AndreaNegro953, that's not really an issue: the version is known from the run header block. We don't need to be able to read the version from an event end block in isolation I think.

**Comment by maxnoe** [comment]
I.e. here:

https://github.com/cta-observatory/pycorsikaio/blob/eef3b78be2ef488843cef50291d525629dac7403/corsikaio/file.py#L31-L49

We get the version and store it, which means it can later be used to parse the event end block.

**Comment by AndreaNegro953** [comment]
Thank you, I was trying to do something similar to the other block and in those cases the version was read from the file. I think I can try to open a branch then

**Comment by maxnoe** [comment]
@AndreaNegro953 Thank you very much.

I would change the function `parse_run_end` to have the signature:

```
def parse_run_end(run_end_bytes, version):
    ...
```

and then call in `CorsikaFile` like this: `self._run_end = parse_run_end(block, self.version)[0]`

**Comment by AndreaNegro953** [comment]
Thank you, but I think there has been a misunderstanding it is the event end datablock not the run end

**Comment by maxnoe** [comment]
Ah, right, but the same principle applies, right?

**Comment by AndreaNegro953** [comment]
Yeah, I think so. Still testing the changes.

**Comment by maxnoe** [comment]
Addressed in #37
