### ISSUE TITLE
corsikaio runs indefinetly while reading in CorsikaParticleFile

### ISSUE THREAD

**Issue by The-Ludwig** [cta-observatory/pycorsikaio#15]
I recently worked with corsika and the `EHIST` option. It seemed to work well, but I produced new simulations and with some of the new files (which can be corrupted/wrong, not sure on that RN) corsikaio just runs indefinetly.
Minimal examples to reproduce:
```python
>>> from tqdm import tqdm
>>> from corsikaio import CorsikaParticleFile

>>> with CorsikaParticleFile('/scratch/lneste/corsika_gt_e5/DAT000006') as cf, tqdm() as pbar:
>>>    for evt in cf:
>>>        for p in evt.particles:
>>>            pbar.update()
542it [03:01,  2.99it/s] 
```
Seems to read in the first 542 particles, but then just doesn't continue the loop. Am I doing something obviously wrong here? 

On some of the other files (produced with the same options) I also get `OSError: EVTH block expected but found b'\x00\x00\x00\x00'` (which I wouldn't consider a bug as of now, as I said, the files could be corrupted).

**Comment by maxnoe** [comment]
> Am I doing something obviously wrong here?

I wouldn't loop over the particles, that's a numpy array... but no, nothing wrong per se here

**Comment by maxnoe** [comment]
There is an endless while loop in `CorsikaFile.__next__` if the file is truncated. Will fix.
