### ISSUE TITLE
Unable to read longitudinal profiles with 0.3.0

### ISSUE THREAD

**Issue by Jean1995** [cta-observatory/pycorsikaio#24]
I am unable to read longitudinal profile date with the new corsikaio version.

I'll use the file `pycorsikaio/tests/resources/corsika757_particle` as an example, and want to execute the following lines of code:

```
PATH = "pycorsikaio/tests/resources/corsika757_particle"
print(corsikaio.__version__)
with CorsikaFile(PATH) as f:
    for e in f:
        print(e.longitudinal['vertical_depth'])
```

With `0.2.6`, the output looks like this:

```
0.2.6
[ 20.  40.  60.  80. 100. 120. 140. 160. 180. 200. 220. 240. 260. 280.
 300. 320. 340. 360. 380. 400. 420. 440. 460. 480. 500. 520. 540. 560.
 580. 600. 620. 640. 660. 680. 700. 720. 740. 760. 780. 800.]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180. 200. 220. 240. 260. 280.
 300. 320. 340. 360. 380. 400. 420. 440. 460. 480. 500. 520. 540. 560.
 580. 600. 620. 640. 660. 680. 700. 720. 740. 760. 780. 800.]
...
```

With `0.3.0`, I only get empty lists:

```
0.3.0
[]
[]
...
```

The problem is identical for all other elements of `longitudinal`

**Comment by maxnoe** [comment]
@Jean1995 Can you confirm that #25 fixes your issue?

**Comment by Jean1995** [comment]
> @Jean1995 Can you confirm that #25 fixes your issue?

Yes, this fixes the issue.
