### ISSUE TITLE
Advertisment

### ISSUE THREAD

**Issue by kbruegge** [cta-observatory/pycorsikaio#3]
This should be made public to a wider audience. We should update the readme a bit and present it in some CTA related telcon.

**Comment by morcuended** [comment]
I agree with Kai, that would be great. I've been working with standard CORSIKA output files for the last months and I missed a user-friendly and well-constructed framework like this back then. I'm sure it will be very useful for all of us.

**Comment by MaxNoe** [comment]
Sure. Just note that the first really usable version of this is just a day old ;-)

**Comment by MaxNoe** [comment]
This is now on PyPI

**Comment by HealthyPear** [comment]
It's also on conda from what I can see.

Anything else remaining to do for this issue?

**Comment by maxnoe** [comment]
Let's close it for now.
