### ISSUE TITLE
Unable to read longitudinal profiles with python3.10

### ISSUE THREAD

**Issue by Jean1995** [cta-observatory/pycorsikaio#31]
The package appears to be incompatible with python3.10.

I'll use the file` pycorsikaio/tests/resources/corsika757_particle `as an example, and want to execute the following lines of code

```
from corsikaio import CorsikaFile
PATH = "pycorsikaio/tests/resources/corsika757_particle"
with CorsikaFile(PATH) as f:
    for e in f:
        print(e.longitudinal['vertical_depth'])
```

which print only a list of empty arrays.
This is identical to the result of issue #24.

With python3.8, everything is fine, the problem only started to appear for python3.10.

**Comment by maxnoe** [comment]
Can you make sure this is not e.g. an old Version of  pzcorsikaio sneaking in from the user path?

Please show:

```
corsikaio.__version__
corsika.__file__
```

and try exporting PYTHONNOUSERSITE=1  if you are using a conda env.

**Comment by maxnoe** [comment]
The CI tests on python 3.10 and the specific test added for #24 passes.

**Comment by Jean1995** [comment]
This was indeed due to the old corsikaio version
